brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path
from todos.views import (
    TodoListView,
    TodoDetailView,
    TodoCreateView,
    TodoUpdateView,
    TodoDeleteView,
    ItemCreateView,
    TodoItemUpdateView,
)

# todolist = TodoList.objects.create(name="Reminders")

urlpatterns = [
    path("", TodoListView.as_view(), name="todo_list_list"),
    path("<int:pk>/", TodoDetailView.as_view(), name="todo_list_detail"),
    path("create/", TodoCreateView.as_view(), name="todo_list_create"),
    path("<int:pk>/edit/", TodoUpdateView.as_view(), name="todo_list_update"),
    path("<int:pk>/delete/", TodoDeleteView.as_view(), name="todo_list_delete"),
    path("items/create/", ItemCreateView.as_view(), name="todo_item_create"),
    path(
        "items/<int:pk>/edit/",
        TodoItemUpdateView.as_view(),
        name="todo_item_update",
    ),
]

todos/models.py
# from pyexpat import model

# from unittest.main import _TestRunner
from django.db import models

# Create your models here.


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList", related_name=("items"), on_delete=models.CASCADE
    )

    def __str__(self):
        return self.task

todos/views.py
# from django.shortcuts import render
from todos.models import TodoItem, TodoList
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


class TodoListView(ListView):
    model = TodoList
    template_name = "todo/list.html"


class TodoDetailView(DetailView):
    model = TodoList
    template_name = "todo/detail.html"


class TodoCreateView(CreateView):
    model = TodoList
    template_name = "todo/create.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])

    # success_url = reverse_lazy("todo_list_list")


class TodoUpdateView(UpdateView):
    model = TodoList
    template_name = "todo/update.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])

    # success_url = reverse_lazy("todo_list_list")


class TodoDeleteView(DeleteView):
    model = TodoList
    template_name = "todo/delete.html"
    fields = ["name"]
    success_url = reverse_lazy("todo_list_list")


class ItemCreateView(CreateView):
    model = TodoItem
    template_name = "todo_item/create.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])


class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = "todo_item/update.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])

todos/templates/todo/create.html
<!DOCTYPE html>
<html>
    <head>
        <title>Create</title>
    </head>
    <body>
        <main>
            <div>
              <h1>Create a new list</h1>
              <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
              </form>
            </div>
          </main>
        
    </body>
</html>

todos/templates/todo/delete.html
<!DOCTYPE html>
<html>
    <head>
        <title>Delete</title>
    </head>
    <body>
        <main >
            <div>
                <h1>Are you sure?</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                        <button class="button">Delete</button>
                </form>
            </div>
        </main>
    </body>
</html>

todos/templates/todo/detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Lists</title>
</head>

<body>
    <main>
        <div>
            <h1>{{ todolist.name }}</h1>
            <p>
            <a href="{% url 'todo_list_update' todolist.pk %}">Edit</a>
            </p>
            <p>
                <a href="{% url 'todo_list_delete' todolist.id %}">Delete</a>
              </p>      
            <h2>Tasks</h2>
            <table>
                <thead>
                <tr>
                    <th>Task<th>
                    <th>Due date<th>
                </tr>
                <thead>
            <tbody>
                {% for item in todolist.items.all %}
                <tr>
                    <td>{{item.task}}</td>
                    <td>{{item.due_date}}</td>
                </tr>
                {% endfor %} 

            </tbody> 
        </table>    
    </div>
    </main> 
</body>

</html>

todos/templates/todo/list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To DO List</title>
</head>

<body>
    <main>
        <div>
          <h1>My Lists</h1>
          <p>
            <a href="{% url 'todo_list_create' %}">Create a new list</a>
          </p>
          <p>
             <a href="{% url 'todo_item_create' %}">Create a new item</a> 
          </p>
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Number of items</th>
              </tr>
            </thead>
            <tbody>
              {% for list in todolist_list %}
                <tr>
                  <td>
                    <a href="{% url 'todo_list_detail' list.id %}">{{ list.name }}</a>
                  </td>
                  <td>{{ list.items.all|length }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </main>
     
</body>

</html>

todos/templates/todo/update.html
<!DOCTYPE html>
<html>
    <head>
        <title>Update</title>
    </head>
    <body>
        <main >
            <div>
                <h1>Update List</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="control">
                        <button class="button">Update</button>
                    </div>
                </form>
        </div>
        </main>
    </body>
</html>

todos/templates/todo_item/create.html
<!DOCTYPE html>
<html>
    <head>
        <title>Create</title>
    </head>
    <body>
        <main>
            <div>
              <h1>Create a new item</h1>
              <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
              </form>
            </div>
          </main>
        
    </body>
</html>

todos/templates/todo_item/update.html
<!DOCTYPE html>
<html>
    <head>
        <title>Update</title>
    </head>
    <body>
        <main>
            <div>
              <h1>Update item</h1>
              <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Update</button>
              </form>
            </div>
          </main>
        
    </body>
</html>